version: '3.8'

services:
  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"
  
  gocci:
    build:
      context: .
      dockerfile: gocci.dockerfile
      args:
        BUILD_REF: "0.0.1"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    ports:
      - "8000-8002:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gocci 